### 05-01-2023
# going back to Dolly Hparams

run_name: instruct-eval-pile-of-law
save_folder: &save_folder oci://mosaicml-internal-checkpoints/sasha/pile-of-law-finetune/{run_name}/checkpoints/
max_seq_len: 4096


# gpu_type: a100_80gb
gpu_num: 8
platform: r1z1
image: mosaicml/examples:llm-latest

integrations:
  - integration_type: wandb
    project: sasha-law
    tags:
    - instruct
    entity: mosaic-ml
  - integration_type: git_repo
    git_repo: sashaDoubov/llm-foundry
    git_branch: sasha/pile-of-law # use your branch
    # git_commit: # OR use your commit hash
    pip_install: -e .[gpu]
    ssh_clone: false # Should be true if using a private repo
  

command: |
  cd llm-foundry/llmfoundry
  composer main.py /mnt/config/parameters.yaml || (echo "Command failed - killing python" && pkill python && exit 1)

parameters:
  # data_local: /tmp/c4
  # data_remote: s3://mosaicml-internal-checkpoints-shared/c4/gpt2-tokenized-2k/
  tokenizer_name: EleutherAI/gpt-neox-20b
  max_seq_len: 4096
  global_seed: 17

  # Run Name
  run_name: # If left blank, will be read from env var $COMPOSER_RUN_NAME

  # Model
  model:
    name: mosaic_gpt
    init_device: meta
    tokenizer_name: ${tokenizer_name}
    d_model: 2048
    n_heads: 16
    n_layers: 24
    mlp_ratio: 4
    max_seq_len: ${max_seq_len}
    vocab_size: 50368
    attn_pdrop: 0.0
    resid_pdrop: 0.0
    emb_pdrop: 0.0
    attn_impl: triton
    alibi: true
    attn_clip_qkv: 6
    no_bias: false
    # low_precision_layernorm: true
    # param_init_fn: kaiming_normal_
    # init_nonlinearity: relu
    # attn_uses_sequence_id: true


  # Tokenizer
  tokenizer:
    name: ${tokenizer_name}
    kwargs:
      model_max_length: ${max_seq_len}

  # Dataloaders
  train_loader:
    name: finetuning
    dataset:
      name: sam-mosaic/dolly_hhrlhf
      split: train
      tokenizer_name: ${tokenizer_name}
      max_seq_length: ${max_seq_len}
      max_seq_len: ${max_seq_len}
      allow_pad_trimming: false
      decoder_only_format: true
      # packing_ratio: 9.0
      shuffle: true
    drop_last: true
    num_workers: 8
    pin_memory: false
    prefetch_factor: 2
    persistent_workers: true
    timeout: 0

  eval_loader:
    name: finetuning
    dataset:
      name: sam-mosaic/dolly_hhrlhf
      split: test
      tokenizer_name: ${tokenizer_name}
      max_seq_length: ${max_seq_len}
      max_seq_len: ${max_seq_len}
      allow_pad_trimming: false
      decoder_only_format: true
      # packing_ratio: 9.0
      shuffle: true
    drop_last: true
    num_workers: 8
    pin_memory: false
    prefetch_factor: 2
    persistent_workers: true
    timeout: 0

  # There is no validation split so we skip eval_loader

  # Optimization
  scheduler:
    name: linear_decay_with_warmup  # linear no warmup is HF default which dolly used
    t_warmup: 50ba  # Dolly
    alpha_f: 0

  optimizer:
    # mimic HF to replicate dolly
    name: decoupled_adamw
    lr: 5.0e-6
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-8
    weight_decay: 0


  algorithms:
    gradient_clipping:
      clipping_type: norm
      clipping_threshold: 1.0

  max_duration: 2ep
  # this turns off eval
  eval_interval: 200ba
  # eval_subset_num_batches: -1
  eval_first: true
  # eval_first: false
  global_train_batch_size: 48  # 6 * numgpus

  # System
  seed: ${global_seed}
  device_eval_batch_size: 8
  device_train_microbatch_size: auto
  precision: amp_bf16

  # Logging
  progress_bar: false
  log_to_console: true
  console_log_interval: 50ba

  callbacks:
    speed_monitor:
      window_size: 10
    runtime_estimator: {}
    lr_monitor: {}
    # memory_monitor: {}
    # optimizer_monitor: {}
    health_checker:
      test_mode: true

  loggers:
    wandb: {}

  save_interval: 1ep
  save_folder: *save_folder
  save_num_checkpoints_to_keep: 1

  autoresume: false
  python_log_level: debug

  icl_tasks:
  -
    label: lambada_openai
    dataset_uri: oci://mosaicml-internal-datasets/icl/clean/clean_lambada_openai.jsonl # ADD YOUR OWN DATASET URI
    num_fewshot:
    - 0
    batch_size: 4
    icl_task_type: language_modeling
    metric_names:
    - InContextLearningLMAccuracy
    prompt_string: '' # this goes at the beginning of each input
    example_delimiter: '\n' # this goes between fewshot examples
    continuation_delimiter: ' ' # this separates contexts from continuations
  -
    label: lambada_standard
    dataset_uri: oci://mosaicml-internal-datasets/icl/clean/clean_lambada_standard.jsonl # ADD YOUR OWN DATASET URI
    num_fewshot:
    - 0
    batch_size: 4
    icl_task_type: language_modeling
    metric_names:
    - InContextLearningLMAccuracy
    prompt_string: '' # this goes at the beginning of each input
    example_delimiter: '\n' # this goes between fewshot examples
    continuation_delimiter: ' ' # this separates contexts from continuations
  # # -
  # #   label: piqa
  # #   dataset_uri:  s3://mosaicml-internal-dataset-lambda/lambada/piqa.jsonl # ADD YOUR OWN DATASET URI
  # #   num_fewshot:
  # #   - 0
  # #   - 1
  # #   - 5
  # #   batch_size: 4
  # #   icl_task_type: multiple_choice
  # #   metric_names:
  # #   - InContextLearningMultipleChoiceAccuracy
  # #   prompt_string: '' # this goes at the beginning of each input
  # #   example_delimiter: '\n' # this goes between fewshot examples
  # #   continuation_delimiter: ' ' # this separates questions from answers
  -
    label: hellaswag
    dataset_uri: oci://mosaicml-internal-datasets/icl/clean/clean_hellaswag.jsonl # ADD YOUR OWN DATASET URI
    num_fewshot:
    - 0
    # - 1
    # - 5
    batch_size: 4
    icl_task_type: multiple_choice
    metric_names:
    - InContextLearningMultipleChoiceAccuracy
    prompt_string: '' # this goes at the beginning of each input
    example_delimiter: '\n' # this goes between fewshot examples
    continuation_delimiter: ' ' # this separates questions from answers
  # # -
  # #   label: arc_easy
  # #   dataset_uri: s3://mosaicml-internal-dataset-lambda/lambada/arc_easy.jsonl # ADD YOUR OWN DATASET URI
  # #   num_fewshot:
  # #   - 0
  # #   - 1
  # #   - 5
  # #   batch_size: 4
  # #   icl_task_type: multiple_choice
  # #   metric_names:
  # #   - InContextLearningMultipleChoiceAccuracy
  # #   prompt_string: '' # this goes at the beginning of each input
  # #   example_delimiter: '\n' # this goes between fewshot examples
  # #   continuation_delimiter: ' ' # this separates questions from answers
  # # -
  # #   label: copa
  # #   dataset_uri: s3://mosaicml-internal-dataset-lambda/lambada/copa.jsonl # ADD YOUR OWN DATASET URI
  # #   num_fewshot:
  # #   - 0
  # #   - 1
  # #   - 5
  # #   batch_size: 4
  # #   icl_task_type: multiple_choice
  # #   metric_names:
  # #   - InContextLearningMultipleChoiceAccuracy
  # #   prompt_string: '' # this goes at the beginning of each input
  # #   example_delimiter: '\n' # this goes between fewshot examples
  # #   continuation_delimiter: ' Answer: ' # this separates questions from answers
  # # -
  # #   label: boolq
  # #   dataset_uri: s3://mosaicml-internal-dataset-lambda/lambada/boolq.jsonl # ADD YOUR OWN DATASET URI
  # #   num_fewshot:
  # #   - 0
  # #   - 1
  # #   - 5
  # #   batch_size: 4
  # #   icl_task_type: language_modeling
  # #   metric_names:
  # #   - InContextLearningLMAccuracy
  # #   prompt_string: '' # this goes at the beginning of each input
  # #   example_delimiter: '\n' # this goes between fewshot examples
  # #   continuation_delimiter: ' Answer: ' # this separates questions from answers
  # # - 
  # #   label: boolq_mc
  # #   dataset_uri: s3://mosaicml-internal-dataset-lambda/lambada/boolq_mc.jsonl
  # #   num_fewshot:
  # #   - 0
  # #   - 1
  # #   - 5
  # #   batch_size: 4
  # #   icl_task_type: multiple_choice
  # #   metric_names:
  # #   - InContextLearningMultipleChoiceAccuracy
  # #   prompt_string: '' # this goes at the beginning of each input
  # #   example_delimiter: '\n' # this goes between fewshot examples
  # #   continuation_delimiter: ' Answer: ' # this separates questions from answers
  # # -
  # #   label: jeopardy_american_history
  # #   dataset_uri: s3://mosaicml-internal-dataset-lambda/factuality/jeopardy/jeopardy_american_history.jsonl # ADD YOUR OWN DATASET URI
  # #   num_fewshot:
  # #   - 0
  # #   - 1
  # #   - 5
  # #   batch_size: 4
  # #   icl_task_type: language_modeling
  # #   metric_names:
  # #   - InContextLearningLMAccuracy
  # #   prompt_string: '' # this goes at the beginning of each input
  # #   example_delimiter: '\n' # this goes between fewshot examples
  # #   continuation_delimiter: ' Answer: ' # this separates questions from answers
  # # -
  # #   label: jeopardy_literature
  # #   dataset_uri: s3://mosaicml-internal-dataset-lambda/factuality/jeopardy/jeopardy_literature.jsonl # ADD YOUR OWN DATASET URI
  # #   num_fewshot:
  # #   - 0
  # #   - 1
  # #   - 5
  # #   batch_size: 4
  # #   icl_task_type: language_modeling
  # #   metric_names:
  # #   - InContextLearningLMAccuracy
  # #   prompt_string: '' # this goes at the beginning of each input
  # #   example_delimiter: '\n' # this goes between fewshot examples
  # #   continuation_delimiter: ' Answer: ' # this separates questions from answers
  # # -
  # #   label: jeopardy_science
  # #   dataset_uri: s3://mosaicml-internal-dataset-lambda/factuality/jeopardy/jeopardy_science.jsonl # ADD YOUR OWN DATASET URI
  # #   num_fewshot:
  # #   - 0
  # #   - 1
  # #   - 5
  # #   batch_size: 4
  # #   icl_task_type: language_modeling
  # #   metric_names:
  # #   - InContextLearningLMAccuracy
  # #   prompt_string: '' # this goes at the beginning of each input
  # #   example_delimiter: '\n' # this goes between fewshot examples
  # #   continuation_delimiter: ' Answer: ' # this separates questions from answers
  # # -
  # #   label: jeopardy_word_origins
  # #   dataset_uri: s3://mosaicml-internal-dataset-lambda/factuality/jeopardy/jeopardy_word_origins.jsonl # ADD YOUR OWN DATASET URI
  # #   num_fewshot:
  # #   - 0
  # #   - 1
  # #   - 5
  # #   batch_size: 4
  # #   icl_task_type: language_modeling
  # #   metric_names:
  # #   - InContextLearningLMAccuracy
  # #   prompt_string: '' # this goes at the beginning of each input
  # #   example_delimiter: '\n' # this goes between fewshot examples
  # #   continuation_delimiter: ' Answer: ' # this separates questions from answers
  # # -
  # #   label: jeopardy_world_history
  # #   dataset_uri: s3://mosaicml-internal-dataset-lambda/factuality/jeopardy/jeopardy_world_history.jsonl # ADD YOUR OWN DATASET URI
  # #   num_fewshot:
  # #   - 0
  # #   - 1
  # #   - 5
  # #   batch_size: 4
  # #   icl_task_type: language_modeling
  # #   metric_names:
  # #   - InContextLearningLMAccuracy
  # #   prompt_string: '' # this goes at the beginning of each input
  # #   example_delimiter: '\n' # this goes between fewshot examples
  # #   continuation_delimiter: ' Answer: ' # this separates questions from answers