integrations:
- integration_type: git_repo
  git_repo: sashaDoubov/llm-foundry
  git_branch: sasha/pile-of-law # use your branch
  # git_commit: # OR use your commit hash
  pip_install: -e .[llm-cpu]
  ssh_clone: false # Should be true if using a private repo

command: |
  # pip install oci-cli
  # oci os bucket get -bn mosaicml-internal-checkpoints/

  cd llm-foundry/llmfoundry/inference
  python convert_composer_to_hf.py \
    --composer_path oci://mosaicml-internal-checkpoints/sasha/mosaic-gpt-1b-gpus-8-Fuj0Wh/checkpoints/ep2-ba15000-rank0.pt \
    --hf_output_path oci://mosaicml-internal-checkpoints/sasha/mosaic-gpt-1b-gpus-8-Fuj0Wh/hf/ \
    --output_precision bf16 \

image: mosaicml/pytorch:1.13.1_cu117-python3.10-ubuntu20.04
optimization_level: 0

# Mosaic Cloud will use run_name (with a unique suffix) to populate the env var $COMPOSER_RUN_NAME
run_name: convert-composer-hf

gpu_num: 8
cluster: r1z1 # replace with your cluster here!